#
# Copyright (C) 2025 The Android Open Source Project
# Copyright (C) 2025 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/a26x

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

# Bootloader
BOARD_VENDOR := samsung
TARGET_SOC := s5e8835
TARGET_BOOTLOADER_BOARD_NAME := s5e8835
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_USES_UEFI := true
TARGET_BOARD_PLATFORM := erd8835

TARGET_CPU_SMP := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true
#TARGET_USES_64_BIT_BINDER := true

# Display
TW_FRAMERATE := 120
TW_MAX_BRIGHTNESS := 612
TW_THEME := portrait_hdpi
TW_DEFAULT_BRIGHTNESS := 255
TARGET_SCREEN_DENSITY := 385
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel/brightness"

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE := bootconfig buildtime_bootconfig=enable loop.max_part=7 androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 4096

# mkbootimg
BOARD_MKBOOTIMG_ARGS:= \
--board=SRPXK14A004 \
--kernel_offset=0x00008000 \
--ramdisk_offset=0x00000000 \
--header_version=$(BOARD_BOOTIMG_HEADER_VERSION) \
--dtb=$(TARGET_PREBUILT_DTB)
#BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/mkbootimg.mk

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 9126805504 # TODO: Fix hardcoded value
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system system system vendor product odm system_ext vendor_dlkm
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 9122611200 # TODO: Fix hardcoded value

# System as root
BOARD_ROOT_EXTRA_FOLDERS := carrier data_mirror debug_ramdisk efs linkerconfig metadata odm_dlkm oem optics postinstall prism second_stage_resources spu system_ext vendor_dlkm system_dlkm
BOARD_SUPPRESS_SECURE_ERASE := true

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TW_PREPARE_DATA_MEDIA_EARLY := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TW_INCLUDE_NTFS_3G := true
TARGET_USES_MKE2FS := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Verified Boot
BOARD_AVB_ENABLE := false
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# Crypto
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 14
TW_INCLUDE_CRYPTO := false
TW_INCLUDE_CRYPTO_FBE := false
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_METADATA_PARTITION := true

# Misc
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_LPTOOLS := true
TW_EXCLUDE_APEX := true
TW_NO_SCREEN_BLANK := true
RECOVERY_SDCARD_ON_DATA := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_NO_BIND_SYSTEM := true
TW_EXTRA_LANGUAGES := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
PRODUCT_ENFORCE_VINTF_MANIFEST := true
TW_USE_LEGACY_BATTERY_SERVICES := true

# Samsung
TW_NO_REBOOT_BOOTLOADER := true
TW_USE_SAMSUNG_HAPTICS := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_FASTBOOTD := true

# Status Bar UI
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := "50"
TW_CUSTOM_CLOCK_POS := "300"
TW_CUSTOM_BATTERY_POS := "750"

# Props
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_RESETPROP := true
TW_NO_LEGACY_PROPS := true
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Logging
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TWRP_EVENT_LOGGING := true

# USB
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_NEW_MINADBD := true

# Orangefox
OF_USE_MAGISKBOOT := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := "1"
OF_FLASHLIGHT_ENABLE := 0
OF_USE_GREEN_LED := 0
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_DONT_PATCH_ON_FRESH_INSTALLATION := 1
OF_NO_RELOAD_AFTER_DECRYPTION := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.0
OF_SCREEN_H := 2400
OF_STATUS_H := 122
OF_STATUS_INDENT_LEFT := 80
OF_STATUS_INDENT_RIGHT := 80
OF_HIDE_NOTCH := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_CHECK_OVERWRITE_ATTEMPTS := 1
OF_FBE_METADATA_MOUNT_IGNORE := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_OTA_BACKUP_STOCK_BOOT_IMAGE := 1
OF_RUN_POST_FORMAT_PROCESS := 1
OF_ADVANCED_SECURITY := 1
OF_FLASHLIGHT_ENABLE := 0
OF_USE_GREEN_LED := 0
OF_QUICK_BACKUP_LIST := /boot;/dtbo;
OF_FORCE_PREBUILT_KERNEL := 1
OF_ENABLE_LPTOOLS := 1
OF_KEEP_DM_VERITY_FORCED_ENCRYPTION := 1
OF_SKIP_DECRYPTED_ADOPTED_STORAGE := 1
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_UNBIND_SDCARD_F2FS := 1

# Skyhawk Recovery - ONLY FOR SKYHAWK RECOVERY PROJECT BUILDING
SHRP_DARK := true
SHRP_FLASH_MAX_BRIGHTNESS := 500
SHRP_DEVICE_CODE := a26x
SHRP_FLASH := 1

# PBRP- ONLY FOR PITCH BLACK RECOVERY PROJECT BUILDING
PB_TORCH_PATH := "/sys/devices/virtual/camera/flash/rear_flash"
PB_TORCH_MAX_BRIGHTNESS := 1

# Version/Maintainer
TW_DEVICE_VERSION := SavedByLight Stable
SHRP_MAINTAINER := SavedByLight
OF_MAINTAINER := SavedByLight
MAINTAINER := SavedByLight
